version: "3.7"
services:
  openwebrx:
    image: jketterl/openwebrx-full:stable
    restart: unless-stopped
    ports:
      - "8073:8073"
    volumes:
      - /openwebrx-settings:/var/lib/openwebrx
    tmpfs:
      # recommended if you're using an SSD
      - /tmp/openwebrx
  codecserver:
    build:
      context: codecserver-mbelib-docker
    restart: unless-stopped
    ports:
      - "1073:1073"
